services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet_db
    volumes:
      - wallet_data:/var/lib/postgresql/data
    networks:
      - wallet-network

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:password@db/wallet_db"
    depends_on:
      - db
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  wallet_data: